### ISSUE TITLE
React, Mui, Vite, Webpack 이 무엇인지 글로 이쁘게 정리한다

### ISSUE THREAD

**Issue by drunkenhw** [car-ffeine/admin#2]
### ✨ Describe

저도 이 프레임워크 라이브러리들을 사용할 때 왜 이걸 쓰는지 이것의 장점과 단점이 무엇인지 알아야지 잘 사용할 수 있을 것 같아서
이것들에 대해 정리할 필요가 있을 것 같습니다.

### ✅ Tasks

- [ ] React에 대해 정리한다
- [ ] Mui에 대해 정리한다
- [ ] Vite에 대해 정리한다
- [ ] Webpack에 대해 정리한다

### 🕰️ Estimated Time of Completion

5시간

### 🙋🏻 More

정리를 어디에 하면 좋을까요
